trigger:
  tags:
    include:
      - '*'

resources:
  containers:
    - container: linux_flatpak
      image: "citraemu/build-environments:linux-flatpak"
      options: --privileged

jobs:
# LinuxFlatPak build
- job: LinuxFlatPak

  pool:
    vmImage: 'ubuntu-16.04'
  container: linux_flatpak
  steps:
  - bash: echo "${SYSTEM_TEAMPROJECTID}"
    displayName: 'Print project ID'
  - bash: /bin/bash -ex ./.travis/linux-flatpak/generate-data.sh
    displayName: 'Generate Flatpak metadata'
  - task: DownloadSecureFile@1
    displayName: 'Fetch secure file'
    inputs:
      secureFile: flatpak_gpg.key
  - task: DownloadSecureFile@1
    displayName: 'Fetch secure file'
    inputs:
      secureFile: flatpak_ssh.key
  - bash: /bin/bash -ex ./.travis/linux-flatpak/docker.sh
    displayName: 'Build and upload Citra Flatpak'
    # secret variables are used here
    env:
      FLATPAK_SSH_HOSTNAME: $(FLATPAK_SSH_HOSTNAME)
      FLATPAK_SSH_PUBLIC_KEY: $(FLATPAK_SSH_PUBLIC_KEY)
      FLATPAK_GPG_KEY_ID: $(FLATPAK_GPG_KEY_ID)
      FLATPAK_SSH_PORT: $(FLATPAK_SSH_PORT)
      FLATPAK_SSH_USER: $(FLATPAK_SSH_USER)
      AZP_TMP_DIR: $(Agent.TempDirectory) # secure files are downloaded to here
    # Azure pipeline's condition expression is very wired
    # the following means:
    # Build.SourceBranch == 'refs/heads/master' && Build.Repository.Uri == 'citra-emu/citra' && PUSH EVENT (IndividualCI)
    # also, 'Build.Repository.Name' is not available prior to the 'steps' section
    # condition: |
    #   and(
    #     eq(variables['Build.Repository.Name'], 'citra-emu/citra'),
    #     in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI')
    #   )
